name: Build and Deploy mdBook

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Install mdBook
        run: |
          curl -sSL https://github.com/rust-lang/mdBook/releases/latest/download/mdbook-linux-x86_64.tar.gz \
          | tar -xz
          sudo mv mdbook /usr/local/bin/

      - name: Build book
        run: mdbook build

      - name: Deploy to GitHub Pages repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DOCS_DEPLOY_TOKEN }}
          external_repository: lightapi/lightapi.github.io
          publish_dir: ./book
          publish_branch: master
